name: glide_dart_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  rxdart: ^0.27.7
  web_socket_channel: ^3.0.0
  uuid: ^4.4.0
  buffer: ^1.2.3
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
